# Generated by Django 4.2.13 on 2024-07-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=20, unique=True)),
                ("customer_name", models.CharField(max_length=100)),
                ("delivery_status", models.CharField(max_length=100)),
            ],
        ),
    ]
