# Generated by Django 4.2.15 on 2024-08-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_status",
        ),
        migrations.AddField(
            model_name="order",
            name="delivered",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_placed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="out_for_delivery",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
