# Generated by Django 4.2.15 on 2024-08-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_order_delivery_status_order_delivered_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivered",
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_placed",
        ),
        migrations.RemoveField(
            model_name="order",
            name="out_for_delivery",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipped",
        ),
        migrations.AddField(
            model_name="order",
            name="expected_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("order_placed", "Order placed"),
                    ("shipped", "Shipped"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                ],
                default="order_placed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
