# Generated by Django 4.2.15 on 2024-08-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_remove_order_delivered_remove_order_order_placed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerOnboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("iot_product_type", models.CharField(max_length=255)),
                ("apns_required", models.IntegerField()),
                ("apn1", models.CharField(blank=True, max_length=255, null=True)),
                ("apn2", models.CharField(blank=True, max_length=255, null=True)),
                ("apn3", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
