# Generated by Django 5.1 on 2024-08-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_customeronboarding"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("iot_product_type", models.CharField(max_length=100)),
                ("solution_document", models.FileField(upload_to="documents/")),
                ("type2_file", models.FileField(upload_to="type2_files/")),
                ("mdb_file", models.FileField(upload_to="mdb_files/")),
            ],
        ),
    ]
